ALTER TABLE products ADD COLUMN original_price INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN short_description TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN preset_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN file_format TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN mobile_compatible INTEGER NOT NULL DEFAULT 1;
ALTER TABLE products ADD COLUMN desktop_compatible INTEGER NOT NULL DEFAULT 1;
ALTER TABLE products ADD COLUMN badge TEXT NOT NULL DEFAULT '';
